services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"

  frontend:
    image: lblod/frontend-group-6-ai-help-me-ipdc
    labels:
      - "logging=true"

  # Our extra services here

  uuid-generation:
    image: redpencil/uuid-generation
    volumes:
      - ./config/uuid-generation/:/config
    environment:
      RUN_CRON_JOBS: "true" # our harvesting is without deltas right now

  embedding:
    image: lblod/group-6-ai-embedding-service

  # Framework support

  resource:
    image: semtech/mu-cl-resources:1.25.0
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - triplestore:database
    environment:
      MU_SPARQL_TIMEOUT: 600
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config/
    labels:
      - "logging=true"
  database:
    image: semtech/sparql-parser:0.0.8
    volumes:
      - ./config/authorization/:/config/
      - ./data/authorization/:/data/
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
