services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"

  frontend:
    image: lblod/frontend-group-6-ai-help-me-ipdc
    labels:
      - "logging=true"

  # Our extra services here

  # yes, I know this configuration isn't okay
  ipdc-local-harvester:
    image: lblod/ldes-client:feature-state-as-triples
    environment:
      # like running in development mode, why?
      NODE_ENV: "development"
      # or trying to load from a local filesystem.  Are you sure that's
      # safe?  You know it isn't unless you know the exact sources
      LDES_BASE: "file:///data/import/dumps/"
      FIRST_PAGE: "file:///data/import-dumps/instantiesnapshot-limit-25-pageNumber-0.json"
      DIRECT_DATABASE_CONNECTION: "http://triplestore:8890/sparql"
      GRAPH_STORE_URL: "http://triplestore:8890/sparql-graph-crud"
      # and bypassing mu-auth for that ricer speed gain
      BYPASS_MU_AUTH: "true"
      LOG_SPARQL_ALL: "false"
      LOG_SPARQL_UPDATES: "false"
      LOG_SPARQL_QUERIES: "false"
    volumes:
      # ok, so you _do_ know the sources of the dumps but it's still dirty
      - ./data/instantiesnapshot-dumps-import/:/data/import-dumps/
      # and you run in development mode because you're overwriting the
      # source code inline?  Why do you even have builds?  It's dirty,
      # it shouldn't be a feature, and it works.  Check the referred
      # source file.
      - ./config/ldes-client-hack/cron-fetch-ldes.ts:/app/cron-fetch-ldes.ts

  # Framework support

  resource:
    image: semtech/mu-cl-resources:1.25.0
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - triplestore:database
    environment:
      MU_SPARQL_TIMEOUT: 600
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config/
    labels:
      - "logging=true"
  database:
    image: semtech/sparql-parser:0.0.8
    volumes:
      - ./config/authorization/:/config/
      - ./data/authorization/:/data/
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
