springdoc:
  swagger-ui:
    path: /v1/swagger

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

orchestrator:
  pipelines:

    - name: triple-store-pipeline
      description: "Requests all existing members from the LDES server and sends them to GraphDB"
      input:
        name: Ldio:LdesClient
        config:
          urls:
            - http://127.0.0.1:5500/instantiesnapshot_limit%3D25%26pageNumber%3D2305.json
          sourceFormat: application/ld+json
      transformers:
        - name: Ldio:SparqlConstructTransformer
          config:
            query: |
              PREFIX ex: <http://example.org/>
              
              CONSTRUCT {
                ?newIRI ?p ?o .
                ?s ?p ?o .
              }
              WHERE {
                {
                  SELECT ?newIRI ?p ?o
                  WHERE {
                  ?s ?p ?o .
                  FILTER(isBlank(?s))
                  BIND(IRI(CONCAT("https://ipdc.tni-vlaanderen.be/resource/", STRUUID())) AS ?newIRI)
                }
              }
                UNION
                {
                  ?s ?p ?o .
                  FILTER(!isBlank(?s))
                }
              }
      outputs:
        - name: Ldio:VirtuosoOut
          config:
            endpoint: http://database:8890/sparql
            graph: http://data.abb.be

logging:
  level:
    com.apicatalog.jsonld: ERROR